### ISSUE TITLE
Please clarify licensing

### ISSUE THREAD

**Issue by bk2204** [twerth/ir_black#3]
I really like this color scheme and have made a few changes to it to make the colors stand out more on my screen. However, the licensing isn't clear, so I'm not sure I'm even allowed to distribute my modified copy. Could you clarify what license this is under, please?

**Comment by twerth** [comment]
Hey Brian, I guess I never gave it a license. So I'll do that right now, let's go with MIT licensing. Tons of people have made variations of ir_black. Atom's default theme is almost identical (not sure if they used ir_black or a variation). Had I known it was going to take off like it did I would of named it "Todd's Magical Theme of Wonder" instead of InfiniteRed Black. Oh well.
